//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoMoveYearMonthFolder.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PhotoSearchMove {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PhotoSearchMove() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoMoveYearMonthFolder.Resources.PhotoSearchMove", typeof(PhotoSearchMove).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CANCEL REQUEST\r\nWait....
        /// </summary>
        internal static string Btn_Cancel_Click_CANCELREQUESTRNWait {
            get {
                return ResourceManager.GetString("Btn_Cancel_Click_CANCELREQUESTRNWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you confirm that you want to stop the processing?.
        /// </summary>
        internal static string Btn_Cancel_Click_StopProcessing {
            get {
                return ResourceManager.GetString("Btn_Cancel_Click_StopProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Canceled..
        /// </summary>
        internal static string Btn_Start_Click_Annullato {
            get {
                return ResourceManager.GetString("Btn_Start_Click_Annullato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Processing canceled by the user..
        /// </summary>
        internal static string Btn_Start_Click_ElaborazioneAnnullataDallUtente {
            get {
                return ResourceManager.GetString("Btn_Start_Click_ElaborazioneAnnullataDallUtente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Processing completed!.
        /// </summary>
        internal static string Btn_Start_Click_ElaborazioneCompletata {
            get {
                return ResourceManager.GetString("Btn_Start_Click_ElaborazioneCompletata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Information.
        /// </summary>
        internal static string Btn_Start_Click_Informazioni {
            get {
                return ResourceManager.GetString("Btn_Start_Click_Informazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Num. of files processed: {0}.
        /// </summary>
        internal static string Btn_Start_Click_NumFileProcessed {
            get {
                return ResourceManager.GetString("Btn_Start_Click_NumFileProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Num. other file processed: {0}&quot;;.
        /// </summary>
        internal static string Btn_Start_Click_NumOtherFileProcessed {
            get {
                return ResourceManager.GetString("Btn_Start_Click_NumOtherFileProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please verify that the source and destination directories are correct..
        /// </summary>
        internal static string Btn_Start_Click_PleaseVerifyDirectoriesAreCorrect {
            get {
                return ResourceManager.GetString("Btn_Start_Click_PleaseVerifyDirectoriesAreCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        internal static string FrmPhotoSearchMove_Cancel {
            get {
                return ResourceManager.GetString("FrmPhotoSearchMove_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Directory Destination.
        /// </summary>
        internal static string FrmPhotoSearchMove_DirectoryDestination {
            get {
                return ResourceManager.GetString("FrmPhotoSearchMove_DirectoryDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Directory Search.
        /// </summary>
        internal static string FrmPhotoSearchMove_DirectorySearch {
            get {
                return ResourceManager.GetString("FrmPhotoSearchMove_DirectorySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exit.
        /// </summary>
        internal static string FrmPhotoSearchMove_Exit {
            get {
                return ResourceManager.GetString("FrmPhotoSearchMove_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The form cannot be closed while processing is in progress..
        /// </summary>
        internal static string FrmPhotoSearchMove_FormClosing_CannotBeClosedWhileProcessingIsInProgress {
            get {
                return ResourceManager.GetString("FrmPhotoSearchMove_FormClosing_CannotBeClosedWhileProcessingIsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Warning.
        /// </summary>
        internal static string FrmPhotoSearchMove_FormClosing_Warning {
            get {
                return ResourceManager.GetString("FrmPhotoSearchMove_FormClosing_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Photo/Video Search. Copy, without duplicates, And Organized to Year - Month.
        /// </summary>
        internal static string FrmPhotoSearchMove_lblComment {
            get {
                return ResourceManager.GetString("FrmPhotoSearchMove_lblComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UI Language:.
        /// </summary>
        internal static string FrmPhotoSearchMove_lblLanguageUI {
            get {
                return ResourceManager.GetString("FrmPhotoSearchMove_lblLanguageUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search Image Selected Root Only.
        /// </summary>
        internal static string FrmPhotoSearchMove_SearchImageSelectedRootOnly {
            get {
                return ResourceManager.GetString("FrmPhotoSearchMove_SearchImageSelectedRootOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select Directory To Image Copy.
        /// </summary>
        internal static string FrmPhotoSearchMove_SelectDirectoryToImageCopy {
            get {
                return ResourceManager.GetString("FrmPhotoSearchMove_SelectDirectoryToImageCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select Directory To Image Search.
        /// </summary>
        internal static string FrmPhotoSearchMove_SelectDirectoryToImageSearch {
            get {
                return ResourceManager.GetString("FrmPhotoSearchMove_SelectDirectoryToImageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start.
        /// </summary>
        internal static string FrmPhotoSearchMove_Start {
            get {
                return ResourceManager.GetString("FrmPhotoSearchMove_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Max Thread: .
        /// </summary>
        internal static string TbMaxThread_Scroll_MaxThread {
            get {
                return ResourceManager.GetString("TbMaxThread_Scroll_MaxThread", resourceCulture);
            }
        }
    }
}
