//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoMoveYearMonthFolder {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logging {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logging() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoMoveYearMonthFolder.Logging", typeof(Logging).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &gt;&gt;&gt; CANCEL REQUEST !!! &lt;&lt;&lt;.
        /// </summary>
        internal static string Btn_Cancel_Click_CANCELREQUEST {
            get {
                return ResourceManager.GetString("Btn_Cancel_Click_CANCELREQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &gt;&gt;&gt; END &gt; NOT &lt; VALID MEDIA &lt;&lt;&lt;.
        /// </summary>
        internal static string Btn_Start_Click_ENDNOTVALIDMEDIA {
            get {
                return ResourceManager.GetString("Btn_Start_Click_ENDNOTVALIDMEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &gt;&gt;&gt; END VALID MEDIA &lt;&lt;&lt;.
        /// </summary>
        internal static string Btn_Start_Click_ENDVALIDMEDIA {
            get {
                return ResourceManager.GetString("Btn_Start_Click_ENDVALIDMEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error.
        /// </summary>
        internal static string Btn_Start_Click_Error {
            get {
                return ResourceManager.GetString("Btn_Start_Click_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &gt;&gt;&gt; ERROR: {0} &lt;&lt;&lt;.
        /// </summary>
        internal static string Btn_Start_Click_ERRORExMessage {
            get {
                return ResourceManager.GetString("Btn_Start_Click_ERRORExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a \r\n---------------------------------\r\n&gt;&gt;&gt; START &gt;&gt; NOT &lt;&lt; VALID MEDIA &lt;&lt;&lt;.
        /// </summary>
        internal static string Btn_Start_Click_STARTNOTVALIDMEDIA {
            get {
                return ResourceManager.GetString("Btn_Start_Click_STARTNOTVALIDMEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &gt;&gt;&gt; START VALID MEDIA &lt;&lt;&lt;.
        /// </summary>
        internal static string Btn_Start_Click_STARTVALIDMEDIA {
            get {
                return ResourceManager.GetString("Btn_Start_Click_STARTVALIDMEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &gt;&gt;&gt; EXIT &lt;&lt;&lt;.
        /// </summary>
        internal static string FrmPhotoSearchMove_FormClosing_EXIT {
            get {
                return ResourceManager.GetString("FrmPhotoSearchMove_FormClosing_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error during processing of {0}: {1}.
        /// </summary>
        internal static string ProcessFileAsync_ErrorDuringProcessingOf {
            get {
                return ResourceManager.GetString("ProcessFileAsync_ErrorDuringProcessingOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Skipped (duplicate confirmed by hash) {0} -&gt; {1}.
        /// </summary>
        internal static string ProcessFileAsync_SkippedDuplicateConfirmedByHash {
            get {
                return ResourceManager.GetString("ProcessFileAsync_SkippedDuplicateConfirmedByHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Skipped (name and size already seen) {0}.
        /// </summary>
        internal static string ProcessFileAsync_SkippedNameAndSizeAlreadySeen {
            get {
                return ResourceManager.GetString("ProcessFileAsync_SkippedNameAndSizeAlreadySeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Skipped (same EXIF UniqueImageID) {0} -&gt; {1}.
        /// </summary>
        internal static string ProcessFileAsync_SkippedSameEXIFUniqueImageID {
            get {
                return ResourceManager.GetString("ProcessFileAsync_SkippedSameEXIFUniqueImageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copied {0} -&gt; {1}.
        /// </summary>
        internal static string ProcessFileAsyncNotValidExt_Copied {
            get {
                return ResourceManager.GetString("ProcessFileAsyncNotValidExt_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copied {0} -&gt; {1}.
        /// </summary>
        internal static string ProcessFileAsyncValidExt_Copied {
            get {
                return ResourceManager.GetString("ProcessFileAsyncValidExt_Copied", resourceCulture);
            }
        }
    }
}
