<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Title>Photo/Video Search Duplicate Copy And Divide Year/Month</Title>
    <Copyright>© 2025 G.L. aka Firefox_1998</Copyright>
    <PackageIcon>photography-icon.png</PackageIcon>
    <Description>This program search "duplicates" photo, video and copy in destination path dividing the files by year and month of shooting</Description>
    <Platforms>x64</Platforms>
    <StartupObject>PhotoMoveYearMonthFolder.Program</StartupObject>
    <AssemblyTitle>PhotoMoveYearMonthFolder</AssemblyTitle>
    <AssemblyCompany>G.L. aka Firefox_1998</AssemblyCompany>
    <AssemblyProduct>PhotoMoveYearMonthFolder</AssemblyProduct>
    <AssemblyCopyright>© 2025 G.L. aka Firefox_1998</AssemblyCopyright>
    <AssemblyDescription>This program search "duplicates" photo, video and copy in destination path dividing the files by year and month of shooting.</AssemblyDescription>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/Firefox-1998/PhotoVideoOrganizer</RepositoryUrl>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <ApplicationIcon>photography-icon-Windows.ico</ApplicationIcon>

  </PropertyGroup>

  <ItemGroup>
    <Content Include="photography-icon-Windows.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\photography-icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MetadataExtractor" Version="2.8.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="About.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="FrmAbout.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Logging.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="PhotoSearchMove.resx">
      <Generator></Generator>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="SetVersion" BeforeTargets="BeforeBuild">
    <PropertyGroup>
      <!-- Giorni dal 1/1/2000 -->
      <Build>$([System.DateTime]::UtcNow.Subtract($([System.DateTime]::Parse("2000-01-01"))).Days)</Build>

      <!-- Secondi dall'inizio della giornata -->
      <Seconds>$([System.DateTime]::UtcNow.TimeOfDay.TotalSeconds)</Seconds>

      <!-- Divisione per 2 e troncamento -->
      <Revision>$([System.Math]::Floor($([MSBuild]::Divide($(Seconds), 2))))</Revision>

      <!-- Componi la versione -->
      <AssemblyVersion>1.0.$(Build).$(Revision)</AssemblyVersion>
      <FileVersion>$(AssemblyVersion)</FileVersion>
    </PropertyGroup>
  </Target>
</Project>